### ISSUE TITLE
Test-fix branch ready for review and QC

### ISSUE THREAD

**Issue by kylebunting** [Microsoft/MCW-App-modernization#17] opened 2018-08-30 14:20 UTC
The august-2018-testfix branch is ready for review and QC.

**Comment by DawnmarieDesJardins** [comment] 2018-09-22 23:55
Thanks Kyle!  Can you take a quick peek at: 
     Step-by-step lab:  Lines 1878 & 1884.  Formatting looks off, I'm not sure if that's what was intended or if the author was trying for that grey box, like in step 11, just underneath.
     Unguided lab: Lines 1218 & 1224 (same as above).  If they're right, just let me know.
     Unguided lab:  Line 1088 - image is not showing up.
Once done, I'll merge this one and update the HTMLs.  We already have the compliance doc, thanks!

**Comment by DDesJardins2** [comment] 2018-10-05 20:42
@kylebunting 
Hey Kyle!  Have you had a chance to review/fix the above?

**Comment by kylebunting** [comment] 2018-10-08 11:57
@DawnmarieDesJardins, changes correcting these formatting issues have been checked in.

**Comment by DDesJardins2** [comment] 2018-10-08 23:14
You're the best Kyle, thanks!  QC complete, branches merged, HTML updated. Closing issue.

**Closed by DDesJardins2** 2018-10-08 23:14 UTC
