### ISSUE TITLE
Exercise 1: Task 1: Step 16 - Configure Firewall for Remote Debugging

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-App-modernization#36] opened 2019-10-15 02:37 UTC
Upon selecting Execute from the SSMS toolbar, a "Configure Firewall for Remote Debugging" dialog appears (Figure 1).

I selected the option "Cancel remote debugging". This did not cancel debugging, but I was able to proceed by selecting the Continue option in the Debug menu. I suggest that the instructions make the user aware of the dialog and how to work around the problem. 

**Figure 1**
![image](https://user-images.githubusercontent.com/1825479/66795146-b09a7980-eed1-11e9-8cf8-8f83f8b40b83.png)

**Comment by timahenning** [comment] 2019-10-22 18:07
Mike,

I have not forgotten about this issue.  We have some updates coming out next week that should address all of the issues you created.

Tim

**Comment by kylebunting** [comment] 2019-10-24 13:47
@snpdev, I am unable to reproduce this and have never seen this issue before. Were you running SSMS from the SqlServer2008 VM created for the hands-on lab? Did you use the ARM template to create the SqlServer2008 VM or follow the manual provisioning steps? The latest pull request makes some changes to the ARM template, so it might be worthwhile to try again using the new template.

**Note**: You will need to wait for the pull request to be completed to retest since the pointers to the ARM template and configuration scripts point to the current Microsoft repo resources.

**Comment by snpdev** [comment] 2019-10-24 13:58
I'll try again using the new template. Thanks

**Comment by timahenning** [comment] 2019-10-31 20:21
@snpdev We are closing this issue.  Let me know if you see the same error again and we will reopen.

**Closed by timahenning** 2019-10-31 20:21 UTC
