### ISSUE TITLE
Validation errors on source server

### ISSUE THREAD

**Issue by mashyoga** [microsoft/MCW-App-modernization#100] opened 2021-09-23 08:35 UTC
Hi,

During Task 1: Perform assessment for migration to Azure SQL Database and attempting to Connect to a Server (step 9) I keep getting: Invalid source server details were specified for the migration. Validator 'Microsoft.SqlServer.Migration.Core.Validators.SupportedDatabaseEnvironmentValidator' failed to validate data

I have checked both Encrypt and Trust Server Certificate.

I then skipped this step and tried: Task 3: Migrate the database schema using the Data Migration Assistant. This time:
"There are validation errors in the source server. Please fix...."

Again, I have checked both Encrypt and Trust Server Certificate.

**Comment by DawnmarieDesJardins** [comment] 2021-09-27 21:23
@mashyoga @timahenning 
Thank you.  Our authors are working on a fix.  We appreciate your patience.

**Comment by timahenning** [comment] 2021-10-05 16:51
I ran through the lab and was not able to reproduce.

**Comment by DawnmarieDesJardins** [comment] 2021-10-11 16:15
Closing issue as unable to reproduce.  @mashyoga - Please rerun and let us know if you're still having trouble.

**Closed by DawnmarieDesJardins** 2021-10-11 16:15 UTC

**Comment by mashyoga** [comment] 2021-10-11 18:10
Will do... Any suggestions on how to capture logging to track if it recurs?
