### ISSUE TITLE
Exercise 3: Task 4: Assign the service principal access to Key Vault - failing with the given command

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-App-modernization#34] opened 2019-09-10 09:43 UTC
[Exercise 3: Task 4: Step 3:](https://github.com/microsoft/MCW-App-modernization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20App%20modernization.md#task-4-assign-the-service-principal-access-to-key-vault)
As per the lab guide, user is asked to run the following command by replacing their key vault name only:
**az keyvault set-policy -n <your-key-vault-name> --spn http://contoso-apps --secret-permissions get list**

But this command gives error if executed by just giving the key vault name. Therefore, we have to replace **"http://contoso-apps"** with the Application id of the given Service Principal.
This way the command gives desired results.

@timahenning Please look into this as we have Workshop Delivery  on 09/12.
Thank You,
Seerat

**Comment by kylebunting** [comment] 2019-09-10 12:31
@SeeratArora I ran through this lab over the weekend and did not have any issues, and have just run the Key Vault portion again, and am unable to reproduce this issue. It does appear that the command above is missing the key vault name the command should look like:

`az keyvault set-policy -n <your-key-vault-name> --spn http://contoso-apps --secret-permissions get list`

Can you please correct the command and try again?

**Comment by kylebunting** [comment] 2019-09-10 12:32
@DawnmarieDesJardins, if they are doing a workshop delivery on 9/12, it would be best to get the test-fix pull request merged in before that, as there were some issues that needed to be fixed which they might run into if they don't have the latest version.

**Comment by DawnmarieDesJardins** [comment] 2019-09-10 20:00
@SeeratArora 
Hello!  I've merged Kyle's test/fix PR and updated the HTML files.  You now have the most current information for your presentation.

**Comment by SeeratArora** [comment] 2019-09-11 17:01
Hi @DawnmarieDesJardins @kylebunting ,
Thanks for the updates, this is working for me now.

**Comment by kylebunting** [comment] 2019-09-11 18:16
Marking issue as resolved and closing.

**Closed by kylebunting** 2019-09-11 18:16 UTC
